# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-24 15:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_title', models.CharField(max_length=200)),
                ('workshop_detail', models.TextField()),
                ('workshop_image', models.FileField(blank=True, null=True, upload_to='')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
