# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-26 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techx', '0002_workshops'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshops',
            name='workshop_intro',
            field=models.CharField(default=False, max_length=2000),
        ),
        migrations.AlterField(
            model_name='workshops',
            name='workshop_detail',
            field=models.TextField(null=True),
        ),
    ]
