# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-26 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techx', '0003_auto_20180626_0703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=1000)),
                ('your_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=1000)),
                ('your_content', models.TextField(max_length=5000)),
                ('mailed_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
