# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-01 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techx', '0004_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='request_a_workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=1000)),
                ('your_email', models.EmailField(max_length=254)),
                ('conact_number', models.CharField(max_length=100)),
                ('institute_name', models.TextField(max_length=5000)),
                ('location', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('workshop', models.CharField(max_length=100)),
                ('request_date', models.DateTimeField()),
            ],
        ),
    ]
