# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-01 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techx', '0005_request_a_workshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_a_workshop',
            name='institute_name',
            field=models.TextField(max_length=500),
        ),
    ]
