# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-01 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techx', '0007_auto_20180702_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_a_workshop',
            name='message',
        ),
        migrations.RemoveField(
            model_name='request_a_workshop',
            name='subject',
        ),
    ]
