# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-01 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techx', '0010_auto_20180702_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_a_workshop',
            name='conact_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='request_a_workshop',
            name='designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='request_a_workshop',
            name='institute_name',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='request_a_workshop',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='request_a_workshop',
            name='workshop',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='request_a_workshop',
            name='your_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='request_a_workshop',
            name='your_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
