# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-04 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techx', '0013_auto_20180704_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='become_a_campus_ambassador_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100, null=True)),
                ('your_email', models.EmailField(max_length=254, null=True)),
                ('contact_number', models.CharField(max_length=100, null=True)),
                ('college_name', models.CharField(max_length=500, null=True)),
                ('department', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('graduating_year', models.CharField(max_length=100, null=True)),
                ('permanent_address', models.TextField(null=True)),
                ('past_experience', models.TextField(null=True)),
                ('request_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
