# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-20 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techx', '0014_become_a_campus_ambassador_db'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='subject',
            new_name='contact_number',
        ),
    ]
