# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-22 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techx', '0015_auto_20180720_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshops',
            old_name='workshop_intro',
            new_name='workshop_about',
        ),
        migrations.RenameField(
            model_name='workshops',
            old_name='workshop_detail',
            new_name='workshop_benefits',
        ),
        migrations.AddField(
            model_name='workshops',
            name='workshop_details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workshops',
            name='workshop_requirements',
            field=models.TextField(null=True),
        ),
    ]
