# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-24 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techx', '0016_auto_20180722_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshops',
            name='workshop_about',
            field=models.TextField(null=True),
        ),
    ]
